<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use ZipArchive;

class ClinGenSyncSubmissions extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'clingen:sync';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Run ClinGen pipeline and create zip file of Excel outputs';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting ClinGen GCI Sync process...');

        // Path to the pipeline script (v2.0 - uses modular Python package)
        $scriptPath = base_path('scripts/run_clingen_pipeline.py');

        if (!file_exists($scriptPath)) {
            $this->error("Pipeline script not found: {$scriptPath}");
            return 1;
        }

        // Prefer the project-local venv (.venv/bin/python3) so we get a known-good
        // interpreter with the right dependencies (mysql-connector-python, openpyxl).
        // Fall back to system python3 for environments where the venv isn't used
        // (e.g. the production Docker image, which installs deps system-wide).
        $venvPython = base_path('.venv/bin/python3');
        $pythonBin = file_exists($venvPython) ? $venvPython : 'python3';
        $this->info("Python: {$pythonBin}");

        // Capture pipeline start time so we can validate XLSX files were regenerated.
        $pipelineStartTime = time();

        // Run the pipeline script
        $this->info('Running ClinGen pipeline...');
        $this->info("Script: {$scriptPath}");
        $output = [];
        $returnCode = 0;

        exec(escapeshellarg($pythonBin) . ' ' . escapeshellarg($scriptPath) . ' 2>&1', $output, $returnCode);

        if ($returnCode !== 0) {
            $this->error('Pipeline script failed with return code: ' . $returnCode);
            $this->line(implode("\n", $output));
            return 1;
        }

        $this->info('Pipeline completed successfully!');

        // Create zip file
        $this->info('Creating zip file...');

        $comparisonDir = base_path('data/clingen/comparison');
        $zipFileName = 'clingen_sync.zip';  // Use fixed filename to avoid accumulation
        $zipPath = storage_path('app/public/' . $zipFileName);

        // Ensure the public storage directory exists
        if (!file_exists(storage_path('app/public'))) {
            mkdir(storage_path('app/public'), 0755, true);
        }

        // Delete any existing clingen_sync zip files to avoid accumulation
        $existingFiles = glob(storage_path('app/public/clingen_sync*.zip'));
        foreach ($existingFiles as $existingFile) {
            if (unlink($existingFile)) {
                $this->info("  Removed old file: " . basename($existingFile));
            }
        }

        $zip = new ZipArchive();

        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            $this->error('Failed to create zip file');
            return 1;
        }

        // Add the Excel files
        $files = [
            'all_current_submissions.xlsx',
            'changed_submissions.xlsx',
        ];

        // Verify each XLSX file exists AND was regenerated by this pipeline run.
        // A stale file indicates the python pipeline silently skipped XLSX generation
        // (e.g. missing openpyxl), and we'd otherwise zip up data from a previous run.
        $filesAdded = 0;
        $staleFiles = [];
        foreach ($files as $file) {
            $filePath = $comparisonDir . '/' . $file;
            if (!file_exists($filePath)) {
                $this->warn("  File not found: {$file}");
                continue;
            }

            $mtime = filemtime($filePath);
            if ($mtime < $pipelineStartTime) {
                $age = $pipelineStartTime - $mtime;
                $staleFiles[] = "{$file} (mtime is {$age}s before pipeline start)";
                continue;
            }

            $zip->addFile($filePath, $file);
            $filesAdded++;
            $this->info("  Added: {$file}");
        }

        if (!empty($staleFiles)) {
            $zip->close();
            unlink($zipPath);
            $this->error('Pipeline did not regenerate all XLSX files. Stale files detected:');
            foreach ($staleFiles as $stale) {
                $this->error("  - {$stale}");
            }
            $this->error('This usually means the python pipeline is missing the `openpyxl` dependency.');
            $this->error('Run: ' . base_path('.venv/bin/pip') . ' install -r ' . base_path('scripts/requirements.txt'));
            return 1;
        }

        $zip->close();

        if ($filesAdded === 0) {
            $this->error('No files were added to the zip archive');
            unlink($zipPath);
            return 1;
        }

        $this->info("Zip file created: {$zipPath}");
        $this->info("Files included: {$filesAdded}");

        // Output the zip filename for the controller to use
        $this->line($zipFileName);

        return 0;
    }
}
