---
# Production environment overrides.

# Container images
gencc_sub_image: ghcr.io/genecurationcoalition/gencc-sub:2.1.4
gencc_search_image: ghcr.io/genecurationcoalition/gencc-search:2.1.5

# Public routing / TLS
gencc_submit_hostname: portal.thegencc.org
gencc_search_hostname: thegencc.org
gencc_search_hostname_redirects:
  - search.thegencc.org
gencc_letsencrypt_cert_name: gencc-prod
gencc_letsencrypt_domains:
  - "{{ gencc_submit_hostname }}"
  - "{{ gencc_search_hostname }}"
  - search.thegencc.org

# Systemd timers for scheduled tasks
gencc_enable_timers: true

# Used to both reset the database from a dump, and trigger the playbook step which runs the release bootstrap.
# gencc_db_restore_source: "gs://gencc-prod/application-private/backups/gencc_sub_baseline_20260205.sql.gz"
# gencc_db_bootstrap_mode: restore_and_migrate
# gencc_db_restore_force: true
