module.exports = {
  apps: [
    {
      name: 'gencc-nginx',
      script: 'nginx',
      args: '-g "daemon off;"',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 2000,
      error_file: './storage/logs/pm2-nginx-error.log',
      out_file: './storage/logs/pm2-nginx-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gencc-php-fpm',
      script: 'php-fpm',
      args: '--nodaemonize',
      instances: 1,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 2000,
      error_file: './storage/logs/pm2-php-fpm-error.log',
      out_file: './storage/logs/pm2-php-fpm-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gencc-queue-worker',
      script: 'artisan',
      interpreter: 'php',
      args: 'queue:work --tries=3 --timeout=3600 --memory=2048 --sleep=3 --max-jobs=1000',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2048M',
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      error_file: './storage/logs/pm2-queue-error.log',
      out_file: './storage/logs/pm2-queue-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ]
};
