[gcp_vms]
gencc-prod-vm

[gcp_vms:vars]
# ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project=clingen-dx --zone=us-east1-b"'

[production:children]
gcp_vms
